namespace SpotifyAPI.Example
{
    partial class LocalControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// clean up resources used.
        /// </summary>
        /// <param name="disposing">True, if managed resources should be deleted; False otherwise.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region generated by the Component Designer Code

        /// <summary> 
        /// Required method for Designer support. 
        /// The contents of this method may not be changed with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.repeatShuffleLabel = new System.Windows.Forms.Label();
            this.timeLabel = new System.Windows.Forms.Label();
            this.isPlayingLabel = new System.Windows.Forms.Label();
            this.volumeLabel = new System.Windows.Forms.Label();
            this.timeProgressBar = new System.Windows.Forms.ProgressBar();
            this.albumLinkLabel = new System.Windows.Forms.LinkLabel();
            this.artistLinkLabel = new System.Windows.Forms.LinkLabel();
            this.titleLinkLabel = new System.Windows.Forms.LinkLabel();
            this.btnExit = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.volDown = new System.Windows.Forms.PictureBox();
            this.volUp = new System.Windows.Forms.PictureBox();
            this.btnPlayPause = new System.Windows.Forms.PictureBox();
            this.btnNext = new System.Windows.Forms.PictureBox();
            this.btnPrev = new System.Windows.Forms.PictureBox();
            this.titleMarquee = new System.Windows.Forms.Timer(this.components);
            this.trackRight = new System.Windows.Forms.LinkLabel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.albumRight = new System.Windows.Forms.LinkLabel();
            this.albumMarquee = new System.Windows.Forms.Timer(this.components);
            this.artistRight = new System.Windows.Forms.LinkLabel();
            this.artistMarquee = new System.Windows.Forms.Timer(this.components);
            this.smallAlbumPicture = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.btnExit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.volDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.volUp)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnPlayPause)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnNext)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnPrev)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.smallAlbumPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            this.SuspendLayout();
            // 
            // repeatShuffleLabel
            // 
            this.repeatShuffleLabel.AutoSize = true;
            this.repeatShuffleLabel.Enabled = false;
            this.repeatShuffleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.repeatShuffleLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.repeatShuffleLabel.Location = new System.Drawing.Point(334, 69);
            this.repeatShuffleLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.repeatShuffleLabel.Name = "repeatShuffleLabel";
            this.repeatShuffleLabel.Size = new System.Drawing.Size(15, 20);
            this.repeatShuffleLabel.TabIndex = 45;
            this.repeatShuffleLabel.Text = "-";
            this.repeatShuffleLabel.Visible = false;
            // 
            // timeLabel
            // 
            this.timeLabel.AutoSize = true;
            this.timeLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.timeLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.timeLabel.Location = new System.Drawing.Point(208, 89);
            this.timeLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.timeLabel.Name = "timeLabel";
            this.timeLabel.Size = new System.Drawing.Size(10, 13);
            this.timeLabel.TabIndex = 44;
            this.timeLabel.Text = "-";
            // 
            // isPlayingLabel
            // 
            this.isPlayingLabel.AutoSize = true;
            this.isPlayingLabel.Enabled = false;
            this.isPlayingLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.isPlayingLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.isPlayingLabel.Location = new System.Drawing.Point(377, 69);
            this.isPlayingLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.isPlayingLabel.Name = "isPlayingLabel";
            this.isPlayingLabel.Size = new System.Drawing.Size(15, 20);
            this.isPlayingLabel.TabIndex = 42;
            this.isPlayingLabel.Text = "-";
            this.isPlayingLabel.Visible = false;
            // 
            // volumeLabel
            // 
            this.volumeLabel.AutoSize = true;
            this.volumeLabel.Enabled = false;
            this.volumeLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.volumeLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.volumeLabel.Location = new System.Drawing.Point(357, 69);
            this.volumeLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.volumeLabel.Name = "volumeLabel";
            this.volumeLabel.Size = new System.Drawing.Size(15, 20);
            this.volumeLabel.TabIndex = 41;
            this.volumeLabel.Text = "-";
            this.volumeLabel.Visible = false;
            // 
            // timeProgressBar
            // 
            this.timeProgressBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.timeProgressBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(214)))), ((int)(((byte)(96)))));
            this.timeProgressBar.Location = new System.Drawing.Point(5, 93);
            this.timeProgressBar.Margin = new System.Windows.Forms.Padding(4);
            this.timeProgressBar.MarqueeAnimationSpeed = 0;
            this.timeProgressBar.Name = "timeProgressBar";
            this.timeProgressBar.Size = new System.Drawing.Size(200, 7);
            this.timeProgressBar.Step = 5;
            this.timeProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
            this.timeProgressBar.TabIndex = 43;
            // 
            // albumLinkLabel
            // 
            this.albumLinkLabel.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.albumLinkLabel.AutoSize = true;
            this.albumLinkLabel.BackColor = System.Drawing.Color.Transparent;
            this.albumLinkLabel.Font = new System.Drawing.Font("Nirmala UI", 6.5F);
            this.albumLinkLabel.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.albumLinkLabel.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.albumLinkLabel.Location = new System.Drawing.Point(86, 36);
            this.albumLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.albumLinkLabel.Name = "albumLinkLabel";
            this.albumLinkLabel.Size = new System.Drawing.Size(11, 13);
            this.albumLinkLabel.TabIndex = 40;
            this.albumLinkLabel.TabStop = true;
            this.albumLinkLabel.Text = "-";
            this.albumLinkLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.albumLinkLabel.MouseEnter += new System.EventHandler(this.albumLinkLabel_MouseEnter);
            this.albumLinkLabel.MouseLeave += new System.EventHandler(this.albumLinkLabel_MouseLeave);
            // 
            // artistLinkLabel
            // 
            this.artistLinkLabel.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.artistLinkLabel.AutoSize = true;
            this.artistLinkLabel.BackColor = System.Drawing.Color.Transparent;
            this.artistLinkLabel.Font = new System.Drawing.Font("Nirmala UI", 6.5F);
            this.artistLinkLabel.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.artistLinkLabel.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.artistLinkLabel.Location = new System.Drawing.Point(86, 22);
            this.artistLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.artistLinkLabel.Name = "artistLinkLabel";
            this.artistLinkLabel.Size = new System.Drawing.Size(11, 13);
            this.artistLinkLabel.TabIndex = 39;
            this.artistLinkLabel.TabStop = true;
            this.artistLinkLabel.Text = "-";
            this.artistLinkLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.artistLinkLabel.MouseEnter += new System.EventHandler(this.artistLinkLabel_MouseEnter);
            this.artistLinkLabel.MouseLeave += new System.EventHandler(this.artistLinkLabel_MouseLeave);
            // 
            // titleLinkLabel
            // 
            this.titleLinkLabel.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.titleLinkLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.titleLinkLabel.AutoSize = true;
            this.titleLinkLabel.BackColor = System.Drawing.Color.Transparent;
            this.titleLinkLabel.Font = new System.Drawing.Font("Nirmala UI", 7.5F, System.Drawing.FontStyle.Bold);
            this.titleLinkLabel.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.titleLinkLabel.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.titleLinkLabel.Location = new System.Drawing.Point(86, 4);
            this.titleLinkLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.titleLinkLabel.Name = "titleLinkLabel";
            this.titleLinkLabel.Size = new System.Drawing.Size(13, 17);
            this.titleLinkLabel.TabIndex = 37;
            this.titleLinkLabel.TabStop = true;
            this.titleLinkLabel.Text = "-";
            this.titleLinkLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.titleLinkLabel.MouseEnter += new System.EventHandler(this.titleLinkLabel_MouseEnter);
            this.titleLinkLabel.MouseLeave += new System.EventHandler(this.titleLinkLabel_MouseLeave);
            // 
            // btnExit
            // 
            this.btnExit.Image = global::SpotifyMiniPlayer.Properties.Resources.exit;
            this.btnExit.Location = new System.Drawing.Point(218, 3);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(23, 20);
            this.btnExit.TabIndex = 52;
            this.btnExit.TabStop = false;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            this.btnExit.MouseEnter += new System.EventHandler(this.btnExit_MouseEnter);
            this.btnExit.MouseLeave += new System.EventHandler(this.btnExit_MouseLeave);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Location = new System.Drawing.Point(231, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(18, 51);
            this.pictureBox1.TabIndex = 51;
            this.pictureBox1.TabStop = false;
            // 
            // volDown
            // 
            this.volDown.Enabled = false;
            this.volDown.Image = global::SpotifyMiniPlayer.Properties.Resources.minus;
            this.volDown.Location = new System.Drawing.Point(377, 56);
            this.volDown.Name = "volDown";
            this.volDown.Size = new System.Drawing.Size(15, 15);
            this.volDown.TabIndex = 50;
            this.volDown.TabStop = false;
            this.volDown.Visible = false;
            // 
            // volUp
            // 
            this.volUp.Enabled = false;
            this.volUp.Image = global::SpotifyMiniPlayer.Properties.Resources.plus;
            this.volUp.Location = new System.Drawing.Point(356, 56);
            this.volUp.Name = "volUp";
            this.volUp.Size = new System.Drawing.Size(15, 15);
            this.volUp.TabIndex = 49;
            this.volUp.TabStop = false;
            this.volUp.Visible = false;
            // 
            // btnPlayPause
            // 
            this.btnPlayPause.Image = global::SpotifyMiniPlayer.Properties.Resources.play1;
            this.btnPlayPause.Location = new System.Drawing.Point(130, 53);
            this.btnPlayPause.Name = "btnPlayPause";
            this.btnPlayPause.Size = new System.Drawing.Size(38, 37);
            this.btnPlayPause.TabIndex = 48;
            this.btnPlayPause.TabStop = false;
            this.btnPlayPause.Click += new System.EventHandler(this.btnPlayPause_Click);
            this.btnPlayPause.MouseEnter += new System.EventHandler(this.btnPlayPause_MouseEnter);
            this.btnPlayPause.MouseLeave += new System.EventHandler(this.btnPlayPause_MouseLeave);
            // 
            // btnNext
            // 
            this.btnNext.Image = global::SpotifyMiniPlayer.Properties.Resources.next1;
            this.btnNext.Location = new System.Drawing.Point(186, 66);
            this.btnNext.Name = "btnNext";
            this.btnNext.Size = new System.Drawing.Size(15, 15);
            this.btnNext.TabIndex = 47;
            this.btnNext.TabStop = false;
            this.btnNext.Click += new System.EventHandler(this.btnNext_Click);
            this.btnNext.MouseEnter += new System.EventHandler(this.btnNext_MouseEnter);
            this.btnNext.MouseLeave += new System.EventHandler(this.btnNext_MouseLeave);
            // 
            // btnPrev
            // 
            this.btnPrev.Image = global::SpotifyMiniPlayer.Properties.Resources.prev1;
            this.btnPrev.Location = new System.Drawing.Point(98, 66);
            this.btnPrev.Name = "btnPrev";
            this.btnPrev.Size = new System.Drawing.Size(15, 15);
            this.btnPrev.TabIndex = 46;
            this.btnPrev.TabStop = false;
            this.btnPrev.Click += new System.EventHandler(this.btnPrev_Click);
            this.btnPrev.MouseEnter += new System.EventHandler(this.btnPrev_MouseEnter);
            this.btnPrev.MouseLeave += new System.EventHandler(this.btnPrev_MouseLeave);
            // 
            // titleMarquee
            // 
            this.titleMarquee.Interval = 25;
            this.titleMarquee.Tick += new System.EventHandler(this.titleMarquee_Tick);
            // 
            // trackRight
            // 
            this.trackRight.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.trackRight.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.trackRight.AutoSize = true;
            this.trackRight.BackColor = System.Drawing.Color.Transparent;
            this.trackRight.Font = new System.Drawing.Font("Nirmala UI", 7.5F, System.Drawing.FontStyle.Bold);
            this.trackRight.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.trackRight.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.trackRight.Location = new System.Drawing.Point(240, 4);
            this.trackRight.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.trackRight.Name = "trackRight";
            this.trackRight.Size = new System.Drawing.Size(13, 17);
            this.trackRight.TabIndex = 53;
            this.trackRight.TabStop = true;
            this.trackRight.Text = "-";
            this.trackRight.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.trackRight.MouseEnter += new System.EventHandler(this.trackRight_MouseEnter);
            this.trackRight.MouseLeave += new System.EventHandler(this.trackRight_MouseLeave);
            // 
            // pictureBox2
            // 
            this.pictureBox2.Location = new System.Drawing.Point(-6, 0);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(96, 67);
            this.pictureBox2.TabIndex = 54;
            this.pictureBox2.TabStop = false;
            // 
            // albumRight
            // 
            this.albumRight.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.albumRight.AutoSize = true;
            this.albumRight.BackColor = System.Drawing.Color.Transparent;
            this.albumRight.Font = new System.Drawing.Font("Nirmala UI", 6.5F);
            this.albumRight.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.albumRight.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.albumRight.Location = new System.Drawing.Point(240, 36);
            this.albumRight.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.albumRight.Name = "albumRight";
            this.albumRight.Size = new System.Drawing.Size(11, 13);
            this.albumRight.TabIndex = 55;
            this.albumRight.TabStop = true;
            this.albumRight.Text = "-";
            this.albumRight.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.albumRight.MouseEnter += new System.EventHandler(this.albumRight_MouseEnter);
            this.albumRight.MouseLeave += new System.EventHandler(this.albumRight_MouseLeave);
            // 
            // albumMarquee
            // 
            this.albumMarquee.Interval = 25;
            this.albumMarquee.Tick += new System.EventHandler(this.albumMarquee_Tick);
            // 
            // artistRight
            // 
            this.artistRight.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.artistRight.AutoSize = true;
            this.artistRight.BackColor = System.Drawing.Color.Transparent;
            this.artistRight.Font = new System.Drawing.Font("Nirmala UI", 6.5F);
            this.artistRight.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.artistRight.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(175)))), ((int)(((byte)(175)))));
            this.artistRight.Location = new System.Drawing.Point(240, 22);
            this.artistRight.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.artistRight.Name = "artistRight";
            this.artistRight.Size = new System.Drawing.Size(11, 13);
            this.artistRight.TabIndex = 56;
            this.artistRight.TabStop = true;
            this.artistRight.Text = "-";
            this.artistRight.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.artistRight.MouseEnter += new System.EventHandler(this.artistRight_MouseEnter);
            this.artistRight.MouseLeave += new System.EventHandler(this.artistRight_MouseLeave);
            // 
            // artistMarquee
            // 
            this.artistMarquee.Interval = 25;
            this.artistMarquee.Tick += new System.EventHandler(this.artistMarquee_Tick);
            // 
            // smallAlbumPicture
            // 
            this.smallAlbumPicture.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.smallAlbumPicture.Location = new System.Drawing.Point(5, 7);
            this.smallAlbumPicture.Margin = new System.Windows.Forms.Padding(4);
            this.smallAlbumPicture.Name = "smallAlbumPicture";
            this.smallAlbumPicture.Size = new System.Drawing.Size(80, 80);
            this.smallAlbumPicture.TabIndex = 38;
            this.smallAlbumPicture.TabStop = false;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Location = new System.Drawing.Point(213, 2);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(37, 22);
            this.pictureBox3.TabIndex = 57;
            this.pictureBox3.TabStop = false;
            this.pictureBox3.Click += new System.EventHandler(this.pictureBox3_Click);
            // 
            // LocalControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.pictureBox3);
            this.Controls.Add(this.smallAlbumPicture);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.btnPlayPause);
            this.Controls.Add(this.btnNext);
            this.Controls.Add(this.btnPrev);
            this.Controls.Add(this.timeLabel);
            this.Controls.Add(this.albumLinkLabel);
            this.Controls.Add(this.artistLinkLabel);
            this.Controls.Add(this.titleLinkLabel);
            this.Controls.Add(this.timeProgressBar);
            this.Controls.Add(this.artistRight);
            this.Controls.Add(this.albumRight);
            this.Controls.Add(this.trackRight);
            this.Controls.Add(this.volDown);
            this.Controls.Add(this.volUp);
            this.Controls.Add(this.repeatShuffleLabel);
            this.Controls.Add(this.isPlayingLabel);
            this.Controls.Add(this.volumeLabel);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "LocalControl";
            this.Size = new System.Drawing.Size(239, 108);
            this.Load += new System.EventHandler(this.LocalControl_Load);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.LocalControl_MouseDown);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.LocalControl_MouseMove);
            this.MouseUp += new System.Windows.Forms.MouseEventHandler(this.LocalControl_MouseUp);
            ((System.ComponentModel.ISupportInitialize)(this.btnExit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.volDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.volUp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnPlayPause)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnNext)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnPrev)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.smallAlbumPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox volDown;
        private System.Windows.Forms.PictureBox volUp;
        private System.Windows.Forms.PictureBox btnPlayPause;
        private System.Windows.Forms.PictureBox btnNext;
        private System.Windows.Forms.PictureBox btnPrev;
        private System.Windows.Forms.Label repeatShuffleLabel;
        private System.Windows.Forms.Label timeLabel;
        private System.Windows.Forms.Label isPlayingLabel;
        private System.Windows.Forms.Label volumeLabel;
        private System.Windows.Forms.ProgressBar timeProgressBar;
        private System.Windows.Forms.LinkLabel albumLinkLabel;
        private System.Windows.Forms.LinkLabel artistLinkLabel;
        private System.Windows.Forms.LinkLabel titleLinkLabel;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox btnExit;
        private System.Windows.Forms.Timer titleMarquee;
        private System.Windows.Forms.LinkLabel trackRight;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.LinkLabel albumRight;
        private System.Windows.Forms.Timer albumMarquee;
        private System.Windows.Forms.LinkLabel artistRight;
        private System.Windows.Forms.Timer artistMarquee;
        private System.Windows.Forms.PictureBox smallAlbumPicture;
        private System.Windows.Forms.PictureBox pictureBox3;
    }
}
